const API_BASE_URL = process.env.EXPO_PUBLIC_API_BASE_URL;
const AUTH_EMAIL = process.env.EXPO_PUBLIC_AUTH_EMAIL;
const AUTH_PASSWORD = process.env.EXPO_PUBLIC_AUTH_PASSWORD;

const KEY_AUTH_TOKEN = 'auth_token';
const KEY_AUTH_USER = 'auth_user';
const KEY_FACTS_STATE = 'facts_state';
const KEY_FACTS_STATE_CAT = 'facts_state_cat';
const KEY_FACTS_FAVORITES = 'facts_favorites';

const SIGN_IN_SUCCESS_REDIRECT_URL = '/facts';
const SIGN_OUT_REDIRECT_URL = '/sign-in';

export {
  API_BASE_URL,
  AUTH_EMAIL,
  AUTH_PASSWORD,
  KEY_AUTH_TOKEN,
  KEY_AUTH_USER,
  KEY_FACTS_STATE,
  KEY_FACTS_STATE_CAT,
  KEY_FACTS_FAVORITES,
  SIGN_IN_SUCCESS_REDIRECT_URL,
  SIGN_OUT_REDIRECT_URL,
};
